### ISSUE TITLE
Incorrect Example Conditional Code?

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-basics-logical-operators-readme#5]
Hello there, I know I might be wrong, but this example seems incorrect:

let user = 'Charles Babbage';
 
let friendCount = 3;
 
let message, messageColor;

if (user && friendCount) {
  message = `Hi ${user}! You have ${friendCount} ${friendCount === 1 ? 'friend' : 'friends'}!`;
} else {
  if (user) {
    message = 'Please sign in.';
  } else {
    message = 'Link up with your friends to get the most out of Flatbook!';
  }
}

If the user does exist, it runs ```message = 'Please sign in```. I checked it on the desktop. When user doesn't exist, it runs the 'link up with your friends' message. Let me know if I am the one incorrect about this.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @AkaKuro4Ever.

You are correct, that if...else statement was incorrect. We have updated the materials so that the example will correctly set the message variable, removed the extra curly braces, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
